# Generated by Django 5.2.12 on 2026-03-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessCard",
            fields=[
                ("id_card", models.AutoField(primary_key=True, serialize=False)),
                ("card_number", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "access_cards",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                ("id_log", models.AutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=10)),
                ("event_time", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "access_logs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id_car", models.AutoField(primary_key=True, serialize=False)),
                ("number_auto", models.CharField(max_length=10)),
                ("vin", models.CharField(blank=True, max_length=50, null=True)),
                ("brand", models.CharField(max_length=50)),
                ("year_release", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "cars",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("id_driver", models.AutoField(primary_key=True, serialize=False)),
                ("surname", models.CharField(max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.CharField(blank=True, max_length=254, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("license_date", models.DateField(blank=True, null=True)),
                ("driver_type", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "drivers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Garage",
            fields=[
                ("id_garage", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("floors_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "garages",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingPlace",
            fields=[
                ("id_place", models.AutoField(primary_key=True, serialize=False)),
                ("number_place", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("place_description", models.CharField(max_length=100)),
                ("is_occupied", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "parking_places",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CurrentParking",
            fields=[
                (
                    "car",
                    models.OneToOneField(
                        db_column="id_car",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="posts.car",
                    ),
                ),
                ("start_time", models.DateTimeField()),
            ],
            options={
                "db_table": "current_parking",
                "managed": False,
            },
        ),
    ]
